//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public string MaDD { get; set; }
        public string MaDuKien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Buoi { get; set; }
    }
}
