//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuKienTT
    {
        public string MaDuKien { get; set; }
        public string MaUser { get; set; }
        public string Tuan { get; set; }
        public string Thu { get; set; }
        public string Ngay { get; set; }
        public string Thang { get; set; }
        public string Buoi { get; set; }
    }
}
