//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webserver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string MaUser { get; set; }
        public string HoTen { get; set; }
        public string TenTaiKhoan { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string MatKhau { get; set; }
        public string MaQuyen { get; set; }
        public string DiaChi { get; set; }
        public string NienKhoa { get; set; }
        public Nullable<System.DateTime> BatDau { get; set; }
    }
}
